### ISSUE TITLE
How to use SAML security along side other authentication mechanisms

### ISSUE THREAD

**Issue by zampettim** [ulisesbocchio/spring-boot-security-saml-samples#11]
How would one configure the SAML security so that is can be used alongside other configurations, like basic auth, in a Spring Boot app? 

I've tried to use a separate static implementation of Spring Boot's WebSecurityConfigurerAdapter to only apply the configuration to a subset of the url paths, (like is documented for other Spring Boot multi-authentication use cases) and I keep getting the following when trying to start the app.

`Caused by: org.springframework.security.config.annotation.AlreadyBuiltException: This object has already been built
	at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:44)
	at com.github.ulisesbocchio.spring.boot.security.saml.bean.SAMLConfigurerBean.init(SAMLConfigurerBean.java:225)
	at com.github.ulisesbocchio.spring.boot.security.saml.bean.SAMLConfigurerBean.init(SAMLConfigurerBean.java:137)`

My implementation looks like and I configure everything else via properties:

>   
    @Configuration  
    @EnableSAMLSSO    
    public static class SAMLSecurityConfiguration extends WebSecurityConfigurerAdapter
    {
        @Bean
        SAMLConfigurerBean saml()
        {
            return new SAMLConfigurerBean();
        }
        
        @Override
        protected void configure(HttpSecurity http) throws Exception
        {
            //http.antMatcher("/saml/**")
            http.httpBasic().disable()
                .csrf().disable()
                .anonymous()
              .and()
                .apply(saml());
        }
    }

**Comment by ulisesbocchio** [comment]
can you please open this in the `spring-boot-security-saml` repo?
