### ISSUE TITLE
About Controllers

### ISSUE THREAD

**Issue by bishnu-zwayam** [ulisesbocchio/spring-boot-security-saml-samples#12]
Why there is two controllers like HomeController and IdPSelectionController?
Need help!

**Comment by ulisesbocchio** [comment]
Did you run the app?? Once you run it you’ll see there’s 3 pages in the app. The landing page, the IDP selection page, and the Home page. That’s why there are multiple controllers

**Comment by bishnu-zwayam** [comment]
Thank you I got it.
So I ran the app and now I am trying to access localhost:9898/home from browser with my ssocircle credential it is not working!
And also I am not getting this key-value pair in properties file
saml.sso.metadata-generator.entity-id=localhost-demo
how this line works?

**Comment by ulisesbocchio** [comment]
That’s the name of my app in SSO circle

**Comment by ulisesbocchio** [comment]
When you go to localhost:8080 and follow the link, then select the sso circle idp and login in sso circle, where do you get back in the app??

**Comment by bishnu-zwayam** [comment]
I registerd in SSOCircle. And then where to set the app name and what else I have to do in SSOCircle?
I did not get your second question!

**Comment by bishnu-zwayam** [comment]
Hello Ulies,
I need your help.
I used your code now I am able to generate SP metadata. Now I have to add it to SSOCircle. So while adding SP metadata to SSOCircle it asking for  FQDN of the ServiceProvider now I am bit confused about it and after that do I have to change something in SP metadata.xml that I am going to upload in SSOCircle. I used your idp-ssocircle.xml (I had to rename it to idp-metadata.xml).

**Comment by saleembashashaik** [comment]
i have deployed this app in tomcat server , can you guys please help me how to get the home page? what is the url to access the home page?

Note : my war file name looks like this spring-boot-security-saml-demo-okta-1.5.4.RELEASE.war

**Comment by kianameikle** [comment]
@saleembashashaik The url to access the homepage of the app is "http://localhost:8080". Assuming your port is set to 8080

**Comment by ulisesbocchio** [comment]
thanks @kianameikle for pitching in.
Are you guys good? Or need more help?
