### ISSUE TITLE
okta spring boot saml and redirect

### ISSUE THREAD

**Issue by AshishHNP** [ulisesbocchio/spring-boot-security-saml-samples#14]
Hi, thanks for the tutorials and all of the work. I have been trying to set this up using Salesforce as IdP, and my spring app SP. I followed instructions to make a mydomain, set up Salesforce as IdP, created a connected app for my spring app. I have all the proper set up on Salesforce end (so I think). And they have an option to download metadata xml which I replaced on the okta tutorial. I updated the Controller to show Salesforce instead of Okta and the URL.
Now i start up the app, select Salesforce, login. On the salesforce side I can see the IdP login history and see it was a success there. On the spring app side, I can see the ACS Url I put in the connected app in salesforce is being redirected to on a successful login (https://localhost:8080/home).
However, this page doesn't load, it just has this page with a 302 in the timeline and it redirects to https://localhost:8080/saml/discovery?entityID=<myentityid>&returnIDParam=idp and refreshing keeps bringing back to this page.
Its very frustrating and not sure what I am doing wrong. I am using the cert and der file that you provided. Not sure if that matters. @ulisesbocchio

**Comment by ulisesbocchio** [comment]
Interesting, do you have a sample app that I can look at? Or maybe you can paste here the logs of your app from the moment you initiate the `SAMLRequest` until you get redirected back.
There are a number of reasons why it wouldn't work. Fortunately, all of the them just need some config tweaking. I'd pay special attention to entityID, signature checking (sha1 vs sha256 certs) and bindings.

**Comment by AshishHNP** [comment]
I realized it was an issue with the ACS Url. I didn't realize the /saml/sso endpoint was being implemented for us by spring and was instead putting the URL to forward to the /home endpoint rather than going to /saml/sso and then having successful redirect to /home.
