### ISSUE TITLE
Keystore Location

### ISSUE THREAD

**Issue by trblft** [ulisesbocchio/spring-boot-security-saml-samples#15]
Hi, you did a really great job, trying to implement it here, using the -demo-props sample, I got one problem though :+1: 
```
saml.sso.key-manager.store-location=classpath:/config/certificate/keystore
saml.sso.key-manager.store-pass=somesecret
```
Using those two keywords fails into Exception 

> Cannot sign outgoing message as no signing credential is set in the context

I also tried this
`saml.sso.key-manager.default-key=saml`
But it says no entry was found though this command
`keytool -list -v -keystore keystore`
Says

> Type Keystore : jks
> Fournisseur Keystore : SUN
> Votre Keystore contient 1 entrÚe(s)
> Nom d'alias : saml
> Date de crÚation : 11 mars 2014
> Type d'entrÚe : keyEntry
> Longueur de cha¯ne du certificat : 1
> Certificat[1]:
> PropriÚtaire : OU=oiosaml-sp, CN=null
> ╔metteur : OU=oiosaml-sp, O=insee-saml, C=fr
> NumÚro de sÚrie : 144b1430c2d
> Valide du : Tue Mar 11 14:09:25 CET 2014 au : Fri Mar 08 14:09:25 CET 2024
> Empreintes de certificat :
>          MD5 :  CE:D5:BB:0F:B7:E7:C0:56:B5:BC:84:14:86:E1:14:7F
>         SHA1: 98:BE:98:62:92:EC:27:05:1F:9B:90:AC:A3:0B:72:A2:05:D5:85:3E

Is there a property I forgot to use a keystore? I first tried your example with pem key and everything worked fine on ssocircle IDP.
Thanks for sharing your work.

**Comment by ulisesbocchio** [comment]
Hi @trblft, thank you for your kind words.

The properties that you need are:
```yaml
saml:
  sso:
    key-manager:
      store-location: classpath:/config/certificate/keystore
      store-pass: somesecret
      default-key: saml
      key-passwords:
        saml: keysecret
```
Or in code:
```java
serviceProvider
.keyManager()
  .storeLocation("classpath:/config/certificate/keystore")
  .storePass("somesecret")
  .defaultKey("saml")
  .keyPassword("saml", "keysecret");
```

You're basically missing to provide the key password, you only provided the store password.
Let me know how it goes.

**Comment by trblft** [comment]
Well... it works! :+1: so thanks a lot! Took me a few minutes to switch to application.yml mode. We're trying to use the -props sample here at INSEE (french national institute of statistics and demography) and we may succeed very soon. Have a nice day.

**Comment by trblft** [comment]
Something strange here, I may have spoken too soon, I get a kind of infinite loop redirection between two urls, here are the debug logs

> 2018-02-08 11:06:55.272 DEBUG 5064 --- [nio-8443-exec-3] o.s.s.saml.storage.HttpSessionStorage    : Storing message a58814ai4ff45idii0h12ic1c3c4f3 to session C8B94EDE2DB55C10359E982998BD2854
> 2018-02-08 11:06:55.272  INFO 5064 --- [nio-8443-exec-3] o.s.security.saml.log.SAMLDefaultLogger  : AuthNRequest;SUCCESS;0:0:0:0:0:0:0:1;https://localhost:8443;https://idp-interne.insee.test/idp/shibboleth;;;

I just call the authentication url

> https://localhost:8443/saml/login?idp=https://idp-interne.insee.test/idp/shibboleth

And then back to the assertionConsumer URL it loops between those two

> https://localhost:8443/saml/SAMLAssertionConsumer
> https://idp-interne.insee.test/idp/profile/SAML2/POST/SSO

I guess I have to change some urls?
