### ISSUE TITLE
Auth0 Integration Sample Written

### ISSUE THREAD

**Issue by arcseldon** [ulisesbocchio/spring-boot-security-saml-samples#17]
@ulisesbocchio - Great library and samples!  Readme documentation too is excellent.
Just wished to point out that I put together an [Auth0 integration](https://auth0.com/) - based on the Okta integration. 

Please [find here](https://github.com/auth0-samples/auth0-java-springboot-security-saml-idp-client), and if interested you could include with this repo, or perhaps point to it in the README?  No worries if not interested, just wished to inform you all the same. Thanks again.

**Comment by ulisesbocchio** [comment]
Absolutely @arcseldon, please feel free to send a pull request with your sample to the samples repo. Thank you for the sample and the comments!
