### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lukashinsch** [ulisesbocchio/spring-boot-security-saml-samples#2]
Hi, thanks for sharing your code, it helped me a lot. I would really appreciate it if you would publish it under an open source licence, so that people can borrow from it more freely.

**Comment by ulisesbocchio** [comment]
I thought I did, you talking about the samples?? Or the actual spring-boot-security-saml library? You want something less restrictive than the Apache license? Tell me which one you think would be best and I'll take a look.
Best,
Uli

**Comment by lukashinsch** [comment]
Thanks for the quick reply.
I'm actually referring to the samples. I have some requirements where I need to configure some non-standard stuff by hand and your sample was a very good starting point for that. Apache2 license would work well for me.

**Comment by ulisesbocchio** [comment]
Yeah, Feel free to use the code in the samples from your projects, I'll add the license file to the repo

**Comment by lukashinsch** [comment]
Great, thanks!
