### ISSUE TITLE
ACS (Consumer) URL is incorrect for ONELOGIN

### ISSUE THREAD

**Issue by shobhitsinghmmt** [ulisesbocchio/spring-boot-security-saml-samples#20]
Hi Ulises,
In readme of spring-security-saml-sample module configuration for **onelogin** ACS url is incorrect.

ACS (Consumer) URL: http://localhost:8080/home is not working, 

it should be:
ACS (Consumer) URL: http://localhost:8080/saml/SSO.

**Comment by ulisesbocchio** [comment]
thanks
