### ISSUE TITLE
Enable / Disable SAML

### ISSUE THREAD

**Issue by Mukup** [ulisesbocchio/spring-boot-security-saml-samples#3]
Hi Ulises,
Is there a way to enable/disable this plugin based on a yml property? 

Thank You,
Rajesh

**Comment by ulisesbocchio** [comment]
Hi Rajesh, there is no way to do that currently through the plugin itself but fortunately you still have a few other options to accomplish the same. You can for instance do something like this:

```java
@EnableSAMLSSO
@ConditionalOnProperty(name = "property.name", havingValue = "true")
public class SAMLSSOConfiguration {
}
```
And import that class in the main application class:

```java
@Import(SAMLSSOConfiguration.class)
@SpringBootApplication
public class MyApplication {
    ...
}
```
The conditional config will basically look for your property and if the property doesn't have the value you want the entire class won't be loaded.
Or, you may choose to disable it this way if you're using `ServiceProviderConfigurerAdapter` or `WebSecurityConfigurerAdapter `:

```java
@Configuration
public static class MyServiceProviderConfig extends ServiceProviderConfigurerAdapter {
        
        @Value("property.name")
        Boolean enableSAML;
       
        @Override
        public void configure(WebSecurity web) {
            if(!enableSAML) {
                web.ignoring().anyRequest();
            }
        }
}
```
This last option has the downside that will load all your SAML config regardless of whether you enable it or not, and it will be disable at the URL level only, but if you're looking for using this for testing, it might be totally acceptable.
The first approach will basically avoid loading all the SAML config.

**Comment by ulisesbocchio** [comment]
did this work for you buddy?
