### ISSUE TITLE
Not able to deploy on standalone Tomcat

### ISSUE THREAD

**Issue by daggubati** [ulisesbocchio/spring-boot-security-saml-samples#6]
Hi Ulises,

I have downloaded the spring boot sample demo with static metadata and I am not able to deploy it on a standalone Tomcat. Please suggest.

**Comment by ulisesbocchio** [comment]
you have to add the config to get a war out of it and whatever hooks you need on the code to support it. Basically just follow the Spring Boot docs to get a deployable WAR out of a spring boot app
